package views.TimKiemManagerFrame;

import Bean.HoKhauBean;
import controllers.TimKiemManagerController.LichSuThayDoiNKController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Objects;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author User
 */
public class LSuThayDoiNhanKhauJFrame extends javax.swing.JFrame {

    private LichSuThayDoiNKController controller;
    private JFrame parentJFrame;
    /**
     * Creates new form TachHoKhau
     * @param parentJFrame
     */
    public LSuThayDoiNhanKhauJFrame(JFrame parentJFrame, JDateChooser tuNgay, JDateChooser denNgay, HoKhauBean hokhauBean) {
        initComponents();
        this.parentJFrame = parentJFrame;
        controller = new LichSuThayDoiNKController(tuNgay, denNgay, hokhauBean, lichSuTableJpn);
        //controller.setTableBotJpn(tableBotJpn);
        //controller.setTableTopJpn(tableTopJpn);
        //controller.init();
        
        controller.setParentJFrame(parentJFrame);
        controller.setDataTable();
        //controller.init();
       
        this.setTitle("Lịch sử thay đổi nhân khẩu");
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close(); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }

    public void close() {
        if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(null, "Are you sure to close?", "Warning!!", JOptionPane.YES_NO_OPTION)) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lichSuTableJpn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lichSuTableJpn.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout gl_lichSuTableJpn = new javax.swing.GroupLayout(lichSuTableJpn);
        lichSuTableJpn.setLayout(gl_lichSuTableJpn);
        gl_lichSuTableJpn.setHorizontalGroup(
            gl_lichSuTableJpn.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gl_lichSuTableJpn.setVerticalGroup(
            gl_lichSuTableJpn.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        			.addContainerGap(30, Short.MAX_VALUE)
        			.addComponent(lichSuTableJpn, GroupLayout.PREFERRED_SIZE, 695, GroupLayout.PREFERRED_SIZE)
        			.addGap(27))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(26, Short.MAX_VALUE)
        			.addComponent(lichSuTableJpn, GroupLayout.PREFERRED_SIZE, 460, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel lichSuTableJpn;
    // End of variables declaration//GEN-END:variables

    public JFrame getParentJFrame() {
        return parentJFrame;
    }
}