package views.TimKiemManagerFrame;

import controllers.HoKhauManagerController.TachHoKhauController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import controllers.TimKiemManagerController.TimNhanKhauController;

/**
 *
 * @author User
 */
public class TimNhanKhauJFrame extends javax.swing.JFrame {

    private TimNhanKhauController controller;
    private JFrame parentJFrame;
    private JComboBox tc1Jcb;
    private JComboBox tc2Jcb;
    private JComboBox tc3Jcb;
    private JTextField tc1Jtf;
    private JTextField tc2Jtf;
    private JTextField tc3Jtf;
    /**
     * Creates new form TachHoKhau
     * @param parentJFrame
     */
    public TimNhanKhauJFrame(JFrame parentJFrame, JComboBox tieuChi1_CB, JComboBox tieuChi2_CB, JComboBox tieuChi3_CB,
    		                 JTextField tieuChi1_text, JTextField tieuChi2_text, JTextField tieuChi3_text) {
        initComponents();
        this.parentJFrame = parentJFrame;
        this.tc1Jcb = tieuChi1_CB;
        this.tc2Jcb = tieuChi2_CB;
        this.tc3Jcb = tieuChi3_CB;
        controller = new TimNhanKhauController(tieuChi1_CB, tieuChi2_CB, tieuChi3_CB,
                                               tieuChi1_text, tieuChi2_text, tieuChi3_text, tableTopJpn);
        controller.setParentJFrame(parentJFrame);
        controller.setDataTable();
        //controller.init();
        this.setTitle("Tìm kiếm");
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close(); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }

    public void close() {
        if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(null, "Are you sure to close?", "Warning!!", JOptionPane.YES_NO_OPTION)) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tableTopJpn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tableTopJpn.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout tableTopJpnLayout = new javax.swing.GroupLayout(tableTopJpn);
        tableTopJpn.setLayout(tableTopJpnLayout);
        tableTopJpnLayout.setHorizontalGroup(
            tableTopJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        tableTopJpnLayout.setVerticalGroup(
            tableTopJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(tableTopJpn, GroupLayout.PREFERRED_SIZE, 638, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(78, Short.MAX_VALUE)
        			.addComponent(tableTopJpn, GroupLayout.PREFERRED_SIZE, 468, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        tableTopJpn.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel tableTopJpn;
    // End of variables declaration//GEN-END:variables

    public JFrame getParentJFrame() {
        return parentJFrame;
    }

}