package views;

import javax.swing.JFrame;

import controllers.NhanKhauManagerPanelController;
import controllers.PhanThuongPanelController;
import views.NhanKhauManagerFrame.AddNewPeopleJFrame;
import views.PhanThuongManagerFrame.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Bằng
 */
public class PhanThuongPanel extends javax.swing.JPanel {
	private PhanThuongPanelController controller = null;
	private JFrame parentFrame;
	
    private PhanThuongPanelController cotroller;
    /**
     * Creates new form PhanThuongPanel
     */
    public PhanThuongPanel(JFrame parentFrame) {
    	this.parentFrame = parentFrame;
        initComponents();
        this.cotroller = new PhanThuongPanelController(tongChauNhoLb, tongHocSinhLb);
        this.cotroller.setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tongChauNhoLb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tongHocSinhLb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setIcon(new ImageIcon(PhanThuongPanel.class.getResource("/Icons/kid_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Số cháu nhỏ trên địa bàn:");

        tongChauNhoLb.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        tongChauNhoLb.setForeground(new java.awt.Color(255, 255, 255));
        tongChauNhoLb.setText("1000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tongChauNhoLb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tongChauNhoLb)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setIcon(new ImageIcon(PhanThuongPanel.class.getResource("/Icons/student_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số các cháu học sinh trên địa bàn");

        tongHocSinhLb.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        tongHocSinhLb.setForeground(new java.awt.Color(255, 255, 255));
        tongHocSinhLb.setText("1000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tongHocSinhLb))
                .addContainerGap(519, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tongHocSinhLb)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        btnLapDSachChauNho = new JButton();
        btnLapDSachChauNho.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		lapDSachChauNhoBtnActionPerformed(e);
        	}
        });
        btnLapDSachChauNho.setText("Lập danh sách");
        btnLapDSachChauNho.setFont(new Font("Arial", Font.BOLD, 14));
        btnLapDSachChauNho.setBackground(Color.WHITE);
        
        btnDanhSachChauNho = new JButton();
        btnDanhSachChauNho.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		DanhSachChauNhoBtnActionPerformed(e);
        	}
        });
        btnDanhSachChauNho.setText("Danh sách đã lập");
        btnDanhSachChauNho.setFont(new Font("Arial", Font.BOLD, 14));
        btnDanhSachChauNho.setBackground(Color.WHITE);
        
        btnLapDSachHS = new JButton();
        btnLapDSachHS.setText("Lập danh sách");
        btnLapDSachHS.setFont(new Font("Arial", Font.BOLD, 14));
        btnLapDSachHS.setBackground(Color.WHITE);
        btnLapDSachHS.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		lapDSachHocSinhBtnActionPerformed(e);
        	}
        });
        
        btnDanhSachHS = new JButton();
        btnDanhSachHS.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		DanhSachHocSinhBtnActionPerformed(e);
        	}
        });
        btnDanhSachHS.setText("Danh sách đã lập");
        btnDanhSachHS.setFont(new Font("Arial", Font.BOLD, 14));
        btnDanhSachHS.setBackground(Color.WHITE);
        
        JButton btnThongKeQua = new JButton();
        btnThongKeQua.setText("Thống kê phần quà");
        btnThongKeQua.setFont(new Font("Arial", Font.BOLD, 14));
        btnThongKeQua.setBackground(Color.WHITE);
        btnThongKeQua.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ThongKeQuaBtnActionPerformed(e);
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(106)
        			.addComponent(btnLapDSachChauNho, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
        			.addComponent(btnDanhSachChauNho)
        			.addGap(140))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(107)
        			.addComponent(btnLapDSachHS, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
        			.addComponent(btnDanhSachHS, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        			.addGap(157))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        			.addGap(6))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(282)
        			.addComponent(btnThongKeQua)
        			.addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnLapDSachChauNho, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnDanhSachChauNho, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        			.addGap(41)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(36)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnLapDSachHS, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnDanhSachHS, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(btnThongKeQua, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addGap(12))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    
    private void lapDSachChauNhoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapDSachChauNhoBtnActionPerformed
        LapDanhSachChauNho lapDSachChauNhoJFrame = new LapDanhSachChauNho(this.controller, this.parentFrame);
        lapDSachChauNhoJFrame.setLocationRelativeTo(null);
        lapDSachChauNhoJFrame.setResizable(false);
        lapDSachChauNhoJFrame.setVisible(true);
    }//GEN-LAST:event_lapDSachChauNhoBtnActionPerformed

    private void DanhSachChauNhoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapDSachChauNhoBtnActionPerformed
        DanhSachChauNho DSachChauNhoJFrame = new DanhSachChauNho(this.controller, this.parentFrame);
        DSachChauNhoJFrame.setLocationRelativeTo(null);
        DSachChauNhoJFrame.setResizable(false);
        DSachChauNhoJFrame.setVisible(true);
    }//GEN-LAST:event_lapDSachChauNhoBtnActionPerformed
    
    private void lapDSachHocSinhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapDSachChauNhoBtnActionPerformed
        LapDanhSachHocSinh lapDSachHocSinhJFrame = new LapDanhSachHocSinh(this.controller, this.parentFrame);
        lapDSachHocSinhJFrame.setLocationRelativeTo(null);
        lapDSachHocSinhJFrame.setResizable(false);
        lapDSachHocSinhJFrame.setVisible(true);
    }//GEN-LAST:event_lapDSachChauNhoBtnActionPerformed
    
    private void DanhSachHocSinhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapDSachChauNhoBtnActionPerformed
        DanhSachHocSinh DSachHocSinhJFrame = new DanhSachHocSinh(this.controller, this.parentFrame);
        DSachHocSinhJFrame.setLocationRelativeTo(null);
        DSachHocSinhJFrame.setResizable(false);
        DSachHocSinhJFrame.setVisible(true);
    }//GEN-LAST:event_lapDSachChauNhoBtnActionPerformed
    
    private void ThongKeQuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapDSachChauNhoBtnActionPerformed
        ThongKePhanQua ThongKeQuaJFrame = new ThongKePhanQua(this.controller, this.parentFrame);
        ThongKeQuaJFrame.setLocationRelativeTo(null);
        ThongKeQuaJFrame.setResizable(false);
        ThongKeQuaJFrame.setVisible(true);
    }//GEN-LAST:event_lapDSachChauNhoBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel tongHocSinhLb;
    private javax.swing.JLabel tongChauNhoLb;
    private JButton btnLapDSachChauNho;
    private JButton btnDanhSachChauNho;
    private JButton btnLapDSachHS;
    private JButton btnDanhSachHS;
}