package views.PhanThuongManagerFrame;

import Bean.NhanKhauBean;
import controllers.LoginController;
import controllers.PhanThuongManagerController.DanhSachHocSinhPanelController;
import controllers.PhanThuongManagerController.LapDanhSachChauNhoController;
import controllers.PhanThuongPanelController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.ChungMinhThuModel;
import models.NhanKhauModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JComboBox;
import javax.swing.JTextPane;


/**
 *
 * @author Hai
 */
public class DanhSachHocSinh extends javax.swing.JFrame {

    /**
     * Creates new form AddNewPeopleJFrame
     */
    private PhanThuongPanelController parentController;
    private JFrame parentFrame;
    private NhanKhauBean nhanKhauBean;
    private DanhSachHocSinhPanelController controller;


    public DanhSachHocSinh(PhanThuongPanelController parentController, JFrame parentJFrame) {
        this.parentController = parentController;
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.nhanKhauBean = new NhanKhauBean();
        initComponents();
        setTitle("Danh sách đã lập");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controller = new DanhSachHocSinhPanelController(tablePanel, textField_2, SuKienJTF, btnSaPhnQu_1, btnSaPhnQu, btnTraoQua, ngayTrao, txtpnA, this);
        controller.setParentJFrame(parentFrame);
        controller.setDataTableTraoQua();
        controller.setText();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close?", "Warning!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    /**
     * @wbp.parser.constructor
     */
    public DanhSachHocSinh(JFrame parentJFrame) {
        this.parentController = new PhanThuongPanelController(){
            /*@Override
            public void refreshData() {
                // do nothing
            }

            @Override
            public void initAction() {
                // do nothing
            }*/
            
            
        };
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.nhanKhauBean = new NhanKhauBean();
        initComponents();
        setTitle("Danh sách đã lập");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controller = new DanhSachHocSinhPanelController(tablePanel, textField_2, SuKienJTF, btnSaPhnQu_1, btnSaPhnQu, btnTraoQua, ngayTrao, txtpnA, this);
        controller.setParentJFrame(parentFrame);
        controller.setDataTableTraoQua();
        controller.setText();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close?", "Warning!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SuKienJTF = new javax.swing.JTextField();
        ConfirmBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ngayTrao = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SuKienJTF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        

        ConfirmBtn.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConfirmBtn.setText("Confirm");
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	confirmBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	cancelBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Năm học:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Ngày trao quà:");
        
        tablePanel = new JPanel();
        GroupLayout gl_tablePanel = new GroupLayout(tablePanel);
        gl_tablePanel.setHorizontalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 302, Short.MAX_VALUE)
        		.addGap(0, 302, Short.MAX_VALUE)
        );
        gl_tablePanel.setVerticalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 224, Short.MAX_VALUE)
        		.addGap(0, 224, Short.MAX_VALUE)
        );
        tablePanel.setLayout(gl_tablePanel);
        
        textField_2 = new JTextField();
        textField_2.setFont(new Font("Arial", Font.PLAIN, 14));
        
        btnSaPhnQu = new JButton();
        btnSaPhnQu.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        btnSaPhnQu.setText("Cập nhật minh chứng");
        btnSaPhnQu.setFont(new Font("Tahoma", Font.PLAIN, 12));
        btnSaPhnQu.setBackground(Color.WHITE);
        
        btnTraoQua = new JButton();
        btnTraoQua.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        btnTraoQua.setText("Trao quà");
        btnTraoQua.setFont(new Font("Tahoma", Font.PLAIN, 12));
        btnTraoQua.setBackground(Color.WHITE);
        
        txtpnA = new JTextPane();
        txtpnA.setEditable(false);
        txtpnA.setFont(new Font("Arial", Font.BOLD, 14));
        txtpnA.setText("Có 7/10 cháu đã có minh chứng \nCó 5/7 cháu đã nhận quà");
        
        btnSaPhnQu_1 = new JButton();
        btnSaPhnQu_1.setText("Sửa phần quà");
        btnSaPhnQu_1.setFont(new Font("Tahoma", Font.PLAIN, 12));
        btnSaPhnQu_1.setBackground(Color.WHITE);
        
        lblDanhSchCc = new JLabel();
        lblDanhSchCc.setText("Danh sách các cháu học sinh trên địa bàn:");
        lblDanhSchCc.setFont(new Font("Arial", Font.BOLD, 14));
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(lblDanhSchCc, GroupLayout.PREFERRED_SIZE, 316, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 273, GroupLayout.PREFERRED_SIZE)
        						.addContainerGap())
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addComponent(jLabel1)
        								.addPreferredGap(ComponentPlacement.UNRELATED)
        								.addComponent(SuKienJTF, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)
        								.addGap(57)
        								.addComponent(jLabel8)
        								.addGap(26)
        								.addComponent(ngayTrao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        							.addComponent(tablePanel, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 680, GroupLayout.PREFERRED_SIZE))
        						.addPreferredGap(ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        									.addComponent(btnTraoQua, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(btnSaPhnQu_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(btnSaPhnQu, Alignment.LEADING))
        								.addGap(105))
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(CancelBtn, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        										.addGap(82)
        										.addComponent(ConfirmBtn, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE))
        									.addComponent(txtpnA, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE))
        								.addGap(60)))))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(37)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(SuKienJTF, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        				.addComponent(ngayTrao, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(lblDanhSchCc, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(tablePanel, GroupLayout.PREFERRED_SIZE, 399, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(txtpnA, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        					.addGap(46)
        					.addComponent(btnSaPhnQu_1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnSaPhnQu, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnTraoQua, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(88)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(CancelBtn, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ConfirmBtn, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))))
        			.addGap(18)
        			.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        			.addGap(23))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	if (JOptionPane.showConfirmDialog(this, "Are you sure to close?", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentFrame.setEnabled(true);
            dispose();
        }
    }
    public void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	if (JOptionPane.showConfirmDialog(this, "Are you sure to confirm?", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentFrame.setEnabled(true);
            dispose();
        }
    }
    
    // su ly su kien nhan nut create
    //GEN-LAST:event_CreateBtnActionPerformed
    
    
    // check cac gia tri duoc nhap vao form
   



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JTextField SuKienJTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser ngayTrao;
    private JTextField textField_2;
    private JButton btnSaPhnQu_1;
    private JLabel lblDanhSchCc;
    private JPanel tablePanel;
    private JButton btnSaPhnQu;
    private JButton btnTraoQua;
    private JTextPane txtpnA;
}