package views.PhanThuongManagerFrame;

import Bean.NhanKhauBean;
import controllers.LoginController;
import controllers.PhanThuongManagerController.DanhSachChauNhoController;
import controllers.PhanThuongManagerController.LapDanhSachChauNhoController;
import controllers.PhanThuongPanelController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.ChungMinhThuModel;
import models.NhanKhauModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JComboBox;
import javax.swing.JTextPane;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;


/**
 *
 * @author Hai
 */
public class DanhSachChauNho extends javax.swing.JFrame {

    /**
     * Creates new form AddNewPeopleJFrame
     */
    private PhanThuongPanelController parentController;
    private JFrame parentFrame;
    private NhanKhauBean nhanKhauBean;
    private DanhSachChauNhoController controller;


    public DanhSachChauNho(PhanThuongPanelController parentController, JFrame parentJFrame) {
        this.parentController = parentController;
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.nhanKhauBean = new NhanKhauBean();
        initComponents();
        setTitle("Danh sách đã lập");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controller = new DanhSachChauNhoController(this, cbNam, cbSuKien, textField_2, tablePanel, thongTin);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    /**
     * @wbp.parser.constructor
     */
    public DanhSachChauNho(JFrame parentJFrame) {
        this.parentController = new PhanThuongPanelController(){
            /*@Override
            public void refreshData() {
                // do nothing
            }
            @Override
            public void initAction() {
                // do nothing
            }*/
            
            
        };
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.nhanKhauBean = new NhanKhauBean();
        initComponents();
        setTitle("Danh sách đã lập");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controller = new DanhSachChauNhoController(this, cbNam, cbSuKien, textField_2, tablePanel, thongTin);
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CancelBtn = new javax.swing.JButton();
        CancelBtn.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		actionCancelPerformed(e);
        	}
        });
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namSinhDateC = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        CancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CancelBtn.setText("Đóng");
        

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Năm:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Ngày trao quà:");
        
        tablePanel = new JPanel();
        GroupLayout gl_tablePanel = new GroupLayout(tablePanel);
        gl_tablePanel.setHorizontalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 302, Short.MAX_VALUE)
        		.addGap(0, 302, Short.MAX_VALUE)
        );
        gl_tablePanel.setVerticalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 224, Short.MAX_VALUE)
        		.addGap(0, 224, Short.MAX_VALUE)
        );
        tablePanel.setLayout(gl_tablePanel);
        
        textField_2 = new JTextField();
        textField_2.setFont(new Font("Arial", Font.PLAIN, 14));
        
        JButton btnSaPhnQu = new JButton();
        btnSaPhnQu.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		controller.suaPhanQua();
        	}
        });
        btnSaPhnQu.setText("Sửa phần quà");
        btnSaPhnQu.setFont(new Font("Tahoma", Font.PLAIN, 12));
        btnSaPhnQu.setBackground(Color.WHITE);
        
        JButton btnTraoQua = new JButton();
        btnTraoQua.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		controller.traoQua(namSinhDateC.getDate());
        	}
        });
        btnTraoQua.setText("Trao quà");
        btnTraoQua.setFont(new Font("Tahoma", Font.PLAIN, 12));
        btnTraoQua.setBackground(Color.WHITE);
        
        cbSuKien = new JComboBox<String>();
        cbSuKien.setFont(new Font("Tahoma", Font.PLAIN, 11));
        
        JLabel lblSKin = new JLabel();
        lblSKin.setText("Sự kiện:");
        lblSKin.setFont(new Font("Arial", Font.BOLD, 14));
        
        thongTin = new JTextPane();
        thongTin.setFont(new Font("Arial", Font.BOLD, 14));
        thongTin.setText("Người tạo: admin\r\nThời gian tạo sự kiện: 30/2/2019\r\nCó 10/12 hộ gia đình có cháu nhỏ \r\nCó 5/10 hộ đã nhận quà");
        
        cbNam = new JComboBox();
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 273, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel1)
        							.addGap(26)
        							.addComponent(cbNam, 0, 252, Short.MAX_VALUE)
        							.addGap(103)
        							.addComponent(lblSKin, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(cbSuKien, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(tablePanel, GroupLayout.PREFERRED_SIZE, 727, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)))
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addPreferredGap(ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(jLabel8)
        										.addPreferredGap(ComponentPlacement.UNRELATED)
        										.addComponent(namSinhDateC, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
        										.addGap(37))
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        											.addComponent(btnTraoQua, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        											.addComponent(btnSaPhnQu, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE))
        										.addGap(133))))
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addGap(53)
        								.addComponent(thongTin, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)
        								.addContainerGap()))
        						.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(CancelBtn, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        							.addGap(148))))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(37)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addComponent(cbSuKien, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addComponent(cbNam, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        				.addComponent(lblSKin, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        			.addGap(46)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(namSinhDateC, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        					.addGap(32)
        					.addComponent(thongTin, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
        					.addGap(73)
        					.addComponent(btnSaPhnQu, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnTraoQua, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(32)
        					.addComponent(CancelBtn, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        				.addComponent(tablePanel, GroupLayout.PREFERRED_SIZE, 399, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        			.addGap(25))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // su ly su kien nhan nut create
    //GEN-LAST:event_CreateBtnActionPerformed
    
    
    // check cac gia tri duoc nhap vao form
	public void actionCancelPerformed(ActionEvent e) {
    	if (JOptionPane.showConfirmDialog(this, "Are you sure to close?", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentFrame.setEnabled(true);
            dispose();
        }
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser namSinhDateC;
    private JTextField textField_2;
    private JComboBox cbNam;
    private JComboBox cbSuKien;
    private JPanel tablePanel ;
    private JTextPane thongTin;
}