package views.PhanThuongManagerFrame;

import Bean.NhanKhauBean;
import controllers.LoginController;
import controllers.PhanThuongManagerController.LapDanhSachChauNhoController;
import controllers.PhanThuongPanelController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.ChungMinhThuModel;
import models.NhanKhauModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JComboBox;
import javax.swing.JTextPane;


/**
 *
 * @author Hai
 */
public class ThongKePhanQua extends javax.swing.JFrame {

    /**
     * Creates new form AddNewPeopleJFrame
     */
    private PhanThuongPanelController parentController;
    private JFrame parentFrame;
    private NhanKhauBean nhanKhauBean;
    private LapDanhSachChauNhoController controller;


    public ThongKePhanQua (PhanThuongPanelController parentController, JFrame parentJFrame) {
        this.parentController = parentController;
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.nhanKhauBean = new NhanKhauBean();
        initComponents();
        setTitle("Thống kê phần quà");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controller = new LapDanhSachChauNhoController();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    /**
     * @wbp.parser.constructor
     */
    public ThongKePhanQua (JFrame parentJFrame) {
        this.parentController = new PhanThuongPanelController(){
            /*@Override
            public void refreshData() {
                // do nothing
            }

            @Override
            public void initAction() {
                // do nothing
            }*/
            
            
        };
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        this.nhanKhauBean = new NhanKhauBean();
        initComponents();
        setTitle("Danh sách đã lập");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controller = new LapDanhSachChauNhoController();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    
    void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SuKienJTF = new javax.swing.JTextField();
        ConfirmBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SuKienJTF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        

        ConfirmBtn.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConfirmBtn.setText("Thống kê");
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Năm:");
        
        JPanel tablePanel = new JPanel();
        GroupLayout gl_tablePanel = new GroupLayout(tablePanel);
        gl_tablePanel.setHorizontalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 302, Short.MAX_VALUE)
        		.addGap(0, 302, Short.MAX_VALUE)
        );
        gl_tablePanel.setVerticalGroup(
        	gl_tablePanel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 224, Short.MAX_VALUE)
        		.addGap(0, 224, Short.MAX_VALUE)
        );
        tablePanel.setLayout(gl_tablePanel);
        
        textField_2 = new JTextField();
        textField_2.setFont(new Font("Arial", Font.PLAIN, 14));
        
        JComboBox<String> GenderJcb = new JComboBox<String>();
        GenderJcb.setFont(new Font("Arial", Font.PLAIN, 14));
        
        JLabel lblSKin = new JLabel();
        lblSKin.setText("Sự kiện:");
        lblSKin.setFont(new Font("Arial", Font.BOLD, 14));
        
        JTextPane txtpnA = new JTextPane();
        txtpnA.setFont(new Font("Arial", Font.BOLD, 14));
        txtpnA.setText("Tổng số lượng phần quà: 50 \nTổng giá trị: 5000000");
        
        tablePanel_1 = new JPanel();
        GroupLayout gl_tablePanel_1 = new GroupLayout(tablePanel_1);
        gl_tablePanel_1.setHorizontalGroup(
        	gl_tablePanel_1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 449, Short.MAX_VALUE)
        		.addGap(0, 449, Short.MAX_VALUE)
        );
        gl_tablePanel_1.setVerticalGroup(
        	gl_tablePanel_1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 425, Short.MAX_VALUE)
        		.addGap(0, 425, Short.MAX_VALUE)
        );
        tablePanel_1.setLayout(gl_tablePanel_1);
        
        textField = new JTextField();
        textField.setFont(new Font("Arial", Font.PLAIN, 14));
        
        lblNmHc = new JLabel();
        lblNmHc.setText("Năm học:");
        lblNmHc.setFont(new Font("Arial", Font.BOLD, 14));
        
        ConfirmBtn_1 = new JButton();
        ConfirmBtn_1.setText("Thống kê");
        ConfirmBtn_1.setFont(new Font("Tahoma", Font.PLAIN, 12));
        ConfirmBtn_1.setBackground(Color.WHITE);
        
        txtpnA_1 = new JTextPane();
        txtpnA_1.setText("Tổng số lượng phần quà: 10 \nTổng giá trị: 500000");
        txtpnA_1.setFont(new Font("Arial", Font.BOLD, 14));
        
        textField_1 = new JTextField();
        textField_1.setFont(new Font("Arial", Font.PLAIN, 14));
        
        lblDanhSchQu = new JLabel();
        lblDanhSchQu.setText("Danh sách quà các hộ:");
        lblDanhSchQu.setFont(new Font("Arial", Font.BOLD, 14));
        
        lblDanhSchQu_2 = new JLabel();
        lblDanhSchQu_2.setText("Danh sách quà các cháu học sinh:");
        lblDanhSchQu_2.setFont(new Font("Arial", Font.BOLD, 14));
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addComponent(lblDanhSchQu, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addComponent(jLabel1)
        								.addPreferredGap(ComponentPlacement.RELATED)
        								.addComponent(SuKienJTF, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE)
        								.addGap(18)
        								.addComponent(lblSKin, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED)
        								.addComponent(GenderJcb, 0, 246, Short.MAX_VALUE))
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addComponent(ConfirmBtn, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
        								.addGap(30)
        								.addComponent(txtpnA, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)))
        						.addGap(55))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 273, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(tablePanel, GroupLayout.PREFERRED_SIZE, 497, GroupLayout.PREFERRED_SIZE)
        					.addGap(55)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(tablePanel_1, GroupLayout.PREFERRED_SIZE, 513, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(lblNmHc, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(ConfirmBtn_1, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
        					.addGap(34)
        					.addComponent(txtpnA_1, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE))
        				.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 273, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblDanhSchQu_2, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE))
        			.addGap(39))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(20)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        					.addGap(34)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(tablePanel_1, 0, 0, Short.MAX_VALUE)
        						.addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        						.addComponent(SuKienJTF, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblSKin, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        						.addComponent(GenderJcb, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblNmHc, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textField, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(ConfirmBtn, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtpnA, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ConfirmBtn_1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtpnA_1, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(56)
        					.addComponent(lblDanhSchQu, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(56)
        					.addComponent(lblDanhSchQu_2, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JTextField SuKienJTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private JTextField textField_2;
    private JPanel tablePanel_1;
    private JTextField textField;
    private JLabel lblNmHc;
    private JButton ConfirmBtn_1;
    private JTextPane txtpnA_1;
    private JTextField textField_1;
    private JLabel lblDanhSchQu;
    private JLabel lblDanhSchQu_2;
}

